// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 11.0.0.0
//  
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharpDox.Plugins.Chm.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using SharpDox.Plugins.Chm;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public partial class StylesheetTemplate : StylesheetTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n\n/* layout */\nhtml, body{\n\tmargin:0;\n\tpadding:0;\n}\n\n#header{\n\tpadding:5px 25px;\n" +
                    "}\n\n#header h2{\n\tmargin:0;\n}\n\n#subheader{\n\tdisplay:block;\n\tbackground: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BreadCrumbBackgroundColor));
            
            #line default
            #line hidden
            this.Write(";\n\tborder-top: 1px solid ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BreadCrumbBorderColor));
            
            #line default
            #line hidden
            this.Write(";\n\tborder-bottom: 1px solid ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BreadCrumbBorderColor));
            
            #line default
            #line hidden
            this.Write(";\n\tpadding: 2px 25px;\n\tmargin:0;\n\tmargin-top:5px;\n\tmargin-bottom:5px;\n}\n\n#subhead" +
                    "er a{\n\ttext-decoration:none;\n\tfont-weight:bold;\n\tcolor: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BreadCrumbLinkColor));
            
            #line default
            #line hidden
            this.Write(";\n\tfont-size:12px;\n}\n\n#subheader a:hover{\n\tcolor: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BreadCrumbLinkHoverColor));
            
            #line default
            #line hidden
            this.Write(";\n}\n\n#content {\n\tpadding: 10px 25px;\n}\n\n.typesite{\n\tdisplay:none;\n}\n\n.box-title{\n" +
                    "\tmargin-top:0;\n}\n\n.namespace-title{\n\tfont-size:1em;\n\tcolor: #AAA;\n}\n\n.syntax-box" +
                    " {\n    background: none repeat scroll 0 0 ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.SyntaxBoxBackgroundColor));
            
            #line default
            #line hidden
            this.Write(";\n    border: 1px solid ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.SyntaxBoxBorderColor));
            
            #line default
            #line hidden
            this.Write(";\n\tcolor: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.SyntaxBoxTextColor));
            
            #line default
            #line hidden
            this.Write(@";
    padding: 5px;
}

.doc-box, .syntax-box, .table-box, .list-box, .text-box {
    margin: 10px 20px;
}

.doc-box p{
	margin:0;
}

.inline{
	margin: 0 25px;
}

.diagram-box {
    text-align: center;
	margin-top: 10px;
}

.divider {
    background-color: #DADADA;
    border-bottom: 1px solid #FFFFFF;
    height: 1px;
    margin: 0.5em 0 1.5em;
}

.divider span {
    background-color: #F58026;
    display: block;
    height: 1px;
    width: 50px;
	overflow:hidden;
}

/* #Tables
================================================== */

	.table-box{
		width: 100%;
	}

	table{
		width: 100%;
		border-spacing:0;
		border-collapse:collapse;
	}

	th{
		background: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TableHeaderBackgroundColor));
            
            #line default
            #line hidden
            this.Write(";\n\t}\n\n\t.even{\n\t\tbackground: #F6F5F1;\n\t}\n\n\ttd{\n\t\tpadding:5px 10px 5px 10px;\n\t}\n\n\tt" +
                    "d p{\n\t\tmargin:0;\n\t}\n\n\tthead{\n\t\tbackground: none repeat scroll 0 0 ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TableHeaderBackgroundColor));
            
            #line default
            #line hidden
            this.Write(";\n\t\tfont-family: \"Segoe UI\";\n\t\tfont-weight: bold;\n\t}\n\t\n\tthead td{\n\t\tborder-bottom" +
                    ": 1px solid ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TableHeaderBorderColor));
            
            #line default
            #line hidden
            this.Write(";\n\t\tborder-top: 1px solid ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TableHeaderBorderColor));
            
            #line default
            #line hidden
            this.Write(";\n\t}\n\t\n\t.icon-column {\n\t\twidth: 15px;\n\t}\n\n/* #Lists\n=============================" +
                    "===================== */\n\n\t.list-box\n\t{\n\t\twidth: 100%;\n\t}\n\n/* #Typography\n======" +
                    "============================================ */\n\tbody {\n\t\tbackground: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.BackgroundColor));
            
            #line default
            #line hidden
            this.Write(";\n\t\tfont: 14px/24px \'Segoe UI\', \'Comic Sans MS\';\n\t\tcolor: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TextColor));
            
            #line default
            #line hidden
            this.Write(";\n\t}\n\t\n\th1, h2, h3, h4, h5, h6 {\n\t\tcolor: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.TextColor));
            
            #line default
            #line hidden
            this.Write(@";
		font: 60px/68px 'Segoe UI Light', 'Comic Sans MS';
	}
	h1 a, h2 a, h3 a, h4 a, h5 a, h6 a { font-weight: inherit; }
	h1 { font-size: 42pt; line-height: 50px; margin-bottom: 14px;}
	h2 { font-size: 20pt; line-height: 40px; margin-bottom: 10px; }
	h3 { font-size: 18pt; line-height: 34px; }
	h4 { font-size: 11pt; font-weight:600; line-height: 30px; margin-bottom: 4px; }
	h5 { font-size: 11pt; line-height: 24px; }
	h6 { font-size: 11pt; line-height: 21px; }

	p { margin: 0 0 20px 0; }
	p img { margin: 0; }
	p.lead { font-size: 21px; line-height: 27px; color: #777;  }

	em { font-style: italic; }
	strong { font-weight: bold; color: #333; }
	small { font-size: 80%; }

	hr { border: solid #ddd; border-width: 1px 0 0; clear: both; margin: 10px 0 30px; height: 0; }


/* #Links
================================================== */
	a, a:visited { color: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.LinkColor));
            
            #line default
            #line hidden
            this.Write("; text-decoration: none; outline: 0; }\n\ta:hover, a:focus { color: ");
            
            #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(ChmConfig.LinkHoverColor));
            
            #line default
            #line hidden
            this.Write(@"; }
	p a, p a:visited { line-height: inherit; }

/* #Markdown
================================================== */
	.markdown img {
	  width: 100%;
	}
	.markdown strong {
	  font-weight: bold;
	}
	.markdown em {
	  font-style: italic;
	}
	.markdown ol {
	  list-style-type: decimal;
	  margin-left: 20px;
	}
	.markdown ul{
		list-style-type: disc;
		margin-left:25px;
		margin-bottom:15px;
	}
	.markdown blockquote {
	  background: #f6f5f1;
	  border: 1px solid #dadada;
	  padding: 5px;
	  margin-top: 15px;
	  margin-bottom: 15px;
	}
	.markdown blockquote p {
	  margin: 0;
	}
	.markdown pre {
	  background: #f6f5f1;
	  border: 1px solid #dadada;
	  padding: 5px;
	  margin-top: 15px;
	  margin-bottom: 15px;
	  font-family: monospace;
	  display: block;
	  overflow-x: auto;
	  overflow-y: hidden;
	}
	.markdown pre p {
	  margin: 0;
	}

");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "E:\Programming\Github\sharpDox\Plugins\ChmExporter\Templates\StylesheetTemplate.tt"
 
public ChmConfig ChmConfig { get; set; }

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "11.0.0.0")]
    public class StylesheetTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
